# Generated by Django 3.0 on 2019-12-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaModel',
            fields=[
                ('id_categoria', models.AutoField(auto_created=True, default=100, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'db_table': 't_categoria',
            },
        ),
    ]
