# Generated by Django 3.0 on 2019-12-18 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabecera_documento',
            fields=[
                ('cd_id', models.AutoField(primary_key=True, serialize=False)),
                ('cd_fecha', models.DateTimeField(auto_now=True)),
                ('cd_nomCli', models.CharField(max_length=45)),
                ('cd_dniCli', models.CharField(max_length=15)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cabera de Documentos',
                'db_table': 't_cabeceraDocumento',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('mesa_id', models.AutoField(primary_key=True, serialize=False)),
                ('mesa_nro', models.IntegerField()),
                ('mesa_est', models.BooleanField(default=True)),
                ('mesa_cant', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Mesas',
                'db_table': 't_mesa',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_desc', models.CharField(max_length=45)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos',
                'db_table': 't_tipo',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usu_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('usu_nom', models.CharField(help_text='Aqui va el nombre completo del usuario', max_length=45)),
                ('usu_hash', models.TextField()),
                ('usu_salt', models.TextField()),
                ('usu_tipo', models.IntegerField(max_length=1)),
                ('usu_email', models.EmailField(max_length=45, unique=True)),
                ('usu_fono', models.CharField(max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'db_table': 't_usuario',
                'ordering': ['usu_nom'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False)),
                ('res_fecha', models.DateTimeField()),
                ('res_dni', models.CharField(max_length=10)),
                ('res_est', models.BooleanField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('mesa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.Mesa')),
                ('usu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.Usuario')),
            ],
            options={
                'verbose_name_plural': 'Reservas',
                'db_table': 't_reserva',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_nom', models.CharField(max_length=50)),
                ('prod_desc', models.TextField()),
                ('prod_img', models.TextField()),
                ('prod_disp', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('tipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.Tipo')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'db_table': 't_producto',
            },
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('precio_id', models.AutoField(primary_key=True, serialize=False)),
                ('precio_inicio', models.DateTimeField()),
                ('precio_fin', models.DateTimeField()),
                ('precio_monto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.Producto')),
            ],
            options={
                'verbose_name_plural': 'Precios',
                'db_table': 't_precio',
            },
        ),
        migrations.CreateModel(
            name='Detalle_documento',
            fields=[
                ('dd_id', models.AutoField(primary_key=True, serialize=False)),
                ('dd_cant', models.IntegerField()),
                ('dd_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('cd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.Cabecera_documento')),
                ('mesa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.Mesa')),
                ('precio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.Precio')),
            ],
            options={
                'verbose_name_plural': 'Detalle de Documentos',
                'db_table': 't_detalleDocumento',
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('asig_id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('mesa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.Mesa')),
                ('usu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.Usuario')),
            ],
            options={
                'verbose_name_plural': 'Asignaciones',
                'db_table': 't_asignacion',
            },
        ),
    ]
