from datetime import datetime
fecha_y_hora = datetime.now()
print(fecha_y_hora)
print(fecha_y_hora.year)
print(fecha_y_hora.month)
print(fecha_y_hora.day)
print(fecha_y_hora.hour)
print(fecha_y_hora.minute)
print(fecha_y_hora.second)
print(fecha_y_hora.microsecond)