# Generated by Django 3.0 on 2019-12-05 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cat_id', models.AutoField(help_text='Id de la categoria', primary_key=True, serialize=False)),
                ('cat_descripcion', models.CharField(help_text='Descripcion de la categoria', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'db_table': 't_categoria',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('subcat_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('subcat_descripcion', models.CharField(help_text='Descripcion de la sub categoria', max_length=100)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productosdb.Categoria')),
            ],
            options={
                'verbose_name_plural': 'Sub Categorias',
                'db_table': 't_subcategoria',
                'unique_together': {('cat_id', 'subcat_descripcion')},
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_desc', models.CharField(help_text='Nombre del producto', max_length=100, unique=True)),
                ('prod_fecha', models.DateTimeField()),
                ('prod_vendido', models.BooleanField(default=False)),
                ('subcat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productosdb.SubCategoria')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'db_table': 't_producto',
            },
        ),
    ]
